all: q1 q2 q3 q4 q5 q6 q7 q8

clean:
	 	rm -f q1 q2 q3 q4 q5 q6 q7 q8

q1:
	gcc -o q1 process_api_q1.c -Wall

q2:
	gcc -o q2 process_api_q2.c -Wall

q3:
	gcc -o q3 process_api_q3.c -Wall

q4:
	gcc -o q4 process_api_q4.c -Wall

q5:
	gcc -o q5 process_api_q5.c -Wall

q6:
	gcc -o q6 process_api_q6.c -Wall

q7:
	gcc -o q7 process_api_q7.c -Wall

q8:
	gcc -o q8 process_api_q8.c -Wall
