all: q1 q2 q3 q4

clean:
	 	rm -f q1 q2 q3 q4

q1:
	gcc -o q1 process_api_q1.c -Wall

q2:
	gcc -o q2 process_api_q2.c -Wall

q3:
	gcc -o q3 process_api_q3.c -Wall

q4:
	gcc -o q4 process_api_q4.c -Wall
